apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-service-sa
  namespace: customer-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/customer-service-sqs-role
  labels:
    app: customer-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: people-service-sa
  namespace: oficina-people-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/people-service-sqs-role
  labels:
    app: people-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hr-service-sa
  namespace: hr-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/hr-service-sqs-role
  labels:
    app: hr-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-service-sa
  namespace: oficina-catalog-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/catalog-service-sqs-role
  labels:
    app: catalog-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: billing-service-sa
  namespace: billing-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/billing-service-sqs-role
  labels:
    app: billing-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: execution-service-sa
  namespace: execution-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/execution-service-sqs-role
  labels:
    app: execution-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: os-service-sa
  namespace: os-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/os-service-sqs-role
  labels:
    app: os-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: maintenance-service-sa
  namespace: maintenance-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/maintenance-service-sqs-role
  labels:
    app: maintenance-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-sa
  namespace: notification-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/notification-service-sqs-role
  labels:
    app: notification-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operations-service-sa
  namespace: operations-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/operations-service-sqs-role
  labels:
    app: operations-service
