apiVersion: v1
kind: Secret
metadata:
  name: catalog-service-secrets
  namespace: catalog-service
  labels:
    app: catalog-service
type: Opaque
data:
  JWT_SECRET: amp3dF9zZWNyZXRfa2V5XzEyMzQ1Njc4OTA=
  NEW_RELIC_LICENSE_KEY: YWJjMTIzNDU2Nzg5MA==
