apiVersion: v1
kind: Secret
metadata:
  name: catalog-service-secrets
  namespace: catalog-service
  labels:
    app: catalog-service
type: Opaque
data:
  DB_HOST: Y2F0YWxvZy1zZXJ2aWNlLXJkcy54eHh4eHgudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
  JWT_SECRET: amp3dF9zZWNyZXRfa2V5XzEyMzQ1Njc4OTA=
  NEW_RELIC_LICENSE_KEY: YWJjMTIzNDU2Nzg5MA==
