apiVersion: v1
kind: ConfigMap
metadata:
  name: execution-service-config
  namespace: execution-service
data:
  SERVER_PORT: "8083"
  SPRING_PROFILES_ACTIVE: "prod"
  LOG_LEVEL: "INFO"
  AWS_REGION: "us-east-1"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "execution_db"
  NEW_RELIC_APP_NAME: "execution-service-prod"
  ENVIRONMENT: "production"
  # Kafka Configuration
  KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka.svc.cluster.local:9092"
  KAFKA_CONSUMER_GROUP: "execution-service-group"
